const BillActionTypes = {
  ADD_BILL: "ADD_BILL",
  SET_BILLS: "SET_BILLS",
  SET_CURRENT_BILL: "SET_CURRENT_BILL",
  TOGGLE_BILL_HIDDEN: "TOGGLE_BILL_HIDDEN",
  TOGGLE_EDIT_BILL_HIDDEN: "TOGGLE_EDIT_BILL_HIDDEN",
  PAY_BILL: "PAY_BILL",
  UPDATE_BILL: "UPDATE_BILL",
};

export default BillActionTypes;
