const TransactionActionTypes = {
  SET_TRANSACTIONS: "SET_TRANSACTIONS",
  ADD_TRANSACTION: "ADD_TRANSACTION",
  ADD_EXPENSE: "ADD_EXPENSE",
  UPDATE_STATUS: "UPDATE_STATUS",
  SET_CURRENT_TRANSACTION: "SET_CURRENT_TRANSACTION",
  TOGGLE_TRANSACTION_HIDDEN: "TOGGLE_TRANSACTION_HIDDEN",
  TOGGLE_EDIT_TRANSACTION_HIDDEN: "TOGGLE_EDIT_TRANSACTION_HIDDEN",
  UPDATE_TRANSACTION: "UPDATE_TRANSACTION",
};

export default TransactionActionTypes;
