const UserActionTypes = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  LOG_OUT_USER: "LOG_OUT_USER",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_IN_START: "SIGN_IN_START",
  SIGN_IN_FAILURE: "SIGN_IN_FAILURE",
};

export default UserActionTypes;
