const AccountActionTypes = {
  ADD_ACCOUNT: "ADD_ACCOUNT",
  SET_ACCOUNTS: "SET_ACCOUNTS",
  REMOVE_ACCOUNTS: "REMOVE_ACCOUNTS",
  SET_CURRENT_ACCOUNT: "SET_CURRENT_ACCOUNT",
  SET_ACCOUNT_BALANCE: "SET_ACCOUNT_BALANCE",
  UPDATE_ACCOUNT_BALANCE: "UPDATE_ACCOUNT_BALANCE",
  UPDATE_ACCOUNT_TOTAL: "UPDATE_ACCOUNT_TOTAL",
};

export default AccountActionTypes;
