const AccountActionTypes = {
  ADD_ACCOUNT: "ADD_ACCOUNT",
  SET_ACCOUNTS: "SET_ACCOUNTS",
  REMOVE_ACCOUNTS: "REMOVE_ACCOUNTS",
  SET_CURRENT_ACCOUNT: "SET_CURRENT_ACCOUNT",
};

export default AccountActionTypes;
